'use client'
import Navbar from '@/components/navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {AnimatePresence, motion as m} from 'framer-motion'
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pathname = usePathname()
  return (
    <html lang="en">
      <body className={`${inter.className} py-24 px-12 lg:px-48`}>
        <Navbar/>
        <AnimatePresence initial={false}>
          <m.div key={pathname}>
          {children}
         </m.div>
        </AnimatePresence>
        </body>
    </html>
  )
}
